melhorias

diff --git a/banana b/banana
--- a/banana
+++ b/banana
@@ -9,6 +9,9 @@
 #MUDANÇAS?
 # changelog.txt
 #
+#VERSIONAMENTO
+# versions.txt
+#
 #SITE
 # https://bananapkg.github.io
 #
@@ -19,8 +22,13 @@
 #================= VARIÁVEIS ESPECIAIS
 ##########################################
 
+# Desabilitando suporte a unicode
+# Para melhor performance.
+export LC_ALL=C
+export LANG=C
+
 export PRG='banana'
-export VERSION='2.2.2'
+export VERSION='2.2.4.5_littlewitchbrown'
 export format_pkg='mz'            # Extensão do pacote
 export descme='info/desc'         # Descrição do pacote
 local_list='var/lib/banana/list'  # Localização da lista
@@ -30,9 +38,11 @@ local_list='var/lib/banana/list'  # Localização da lista
 ########################################
 
 readonly red='\033[31;1m'
+readonly yellow='\033[33;1m'
 readonly blue='\033[34;1m'
-readonly cyan='\033[36;1m'
 readonly pink='\033[35;1m'
+readonly cyan='\033[36;1m'
+readonly white='\033[37;1m'
 readonly end='\033[m'
 
 ########################################
@@ -57,6 +67,8 @@ done
 dirlist='/var/lib/banana/list'       # Lista do pacote 'pack.list'
 dirdesc='/var/lib/banana/desc'       # Descrição do pacote 'pack.desc'
 dirremove='/var/lib/banana/remove'   # Script de remoção do pacote 'rm.sh'
+dirmzinstalled='/var/cache/mz/installed'
+dirmzremoved='/var/cache/mz/removed'
 
 ########################################
 #===============TESTES
@@ -72,18 +84,24 @@ else
     HELP="_HELP_US"
 fi
 
+test -d ${dirlist}        || mkdir -p ${dirlist}
+test -d ${dirdesc}        || mkdir -p ${dirdesc}
+test -d ${dirremove}      || mkdir -p ${dirremove}
+test -d ${dirmzinstalled} || mkdir -p ${dirmzinstalled}
+test -d ${dirmzremoved}   || mkdir -p ${dirmzremoved}
+
 # Inicializando o programa em silêncio...
- _VERBOSE '0'
- 
+_VERBOSE '0'
+
 # Verificando quais argumentos passados pelo usuário
 # para pegar as variáveis necessárias
 for entry_parameter; do
     if [[ "$entry_parameter" = '-y' ]]; then
         AUTO_YES='1'
-    elif [[ "$entry_parameter" = '-v' ]] || [[ "$entry_parameter"  = '--verbose' ]]; then
+    elif [[ "$entry_parameter" = '-v' ]] || [[ "$entry_parameter"  = 'verbose' ]]; then
         VERBOSE='1'
         _VERBOSE '1'
-    elif [[ "$entry_parameter" = '-ol' ]] || [[ "$entry_parameter" = '--one-line' ]]; then
+    elif [[ "$entry_parameter" = '-ol' ]] || [[ "$entry_parameter" = 'one-line' ]]; then
         ONE_LINE='1'
     else
         new_argument+=("$entry_parameter")
@@ -99,7 +117,7 @@ case "$1" in
     -c|create)
        shift # Rebaixando
        _INPUT_NULL_PARAMETER "$1" # Se ta nulo o help precisa ser chamado =)
-       
+
        # Se nome do pacote ter espaços não deve continuar
        if [[ "$@" =~ .*[[:space:]]+.*-.* ]]; then
            echo -e "${red}[Error!]${end} Unexpected character."
@@ -108,12 +126,15 @@ case "$1" in
            echo "If you need more HELP, use -h or --help"
            exit 1
        fi
-       
+
        # Se nome do pacote não for letras ou se tiver
        # espaços entre outras coisas, não pode continuar.
        _NAME_FORMAT_PKG "$1" || exit 1
-       
-       check_var="$(grep -o '-' <<< "$1" | wc -l)"
+
+       # Verificando quantos '-' existem e fazendo contagem
+       # com _WC
+       check_var="$(printf '%s\n' ${1//[a-zA-Z0-9._|\\()@#\!~%;:]/ })"
+       check_var="$(_WC ${check_var})"
        if [[ "$check_var" -lt '2' || "$check_var" -gt '2'  ]]; then
            echo -e "${red}[Error!]${end} Unexpected ' - ' Count."
            echo -e "USE ONLY TWO ' ${red}-${end} ' In the name of your package."
@@ -134,9 +155,11 @@ case "$1" in
 
     -g|generate)
         shift
-        # Verificando se tem traços a mais
+        # Verificando se tem traços '-' a mais
         # E dando um sermão ;D
-        check_var="$(grep -o '-' <<< "$1" | wc -l)"
+
+        check_var="$(printf '%s\n' ${1//[a-zA-Z0-9._|\\()@#\!~%;:]/ })"
+        check_var="$(_WC ${check_var})"
         if [[ -n "$1" ]] && [[ "$check_var" -lt '2' || "$check_var" -gt '2' ]]; then
             echo -e "${red}[ERROR]${end} OPS! Could not generate file desc..."
             echo -e "The Perfect Format name is: banana -g ${blue}name-version-build${end}"
@@ -164,9 +187,13 @@ case "$1" in
         shift # Rebaixe baby
         _INPUT_NULL_PARAMETER "$1" # Se ta nulo o help precisa ser chamado =)
         while [[ -n "$1" ]]; do
-            _NAME_FORMAT_PKG "$1" || exit 1 # Função de configuração de entrada!
-            [[ ! -e "$1" ]] && { echo -e "${red}[ERROR]${end} Do not cheat me! This Package dont exist."; exit 1 ;}
+           _NAME_FORMAT_PKG "$1" || exit 1 # Função de configuração de entrada!
+           [[ ! -e "$1" ]] && { echo -e "${red}[ERROR]${end} Do not cheat me! This Package dont exist."; exit 1 ;}
+            _VERIFY_PACK_IS_XZ "$1" || exit 1 # Pacote É comprimido com XZ?
             _INSTALL_PKG "$1"  || exit 1
+            retval=${?}
+            [[ $retval = 0 ]] && touch $dirmzinstalled/${1}
+            [[ $retval = 0 ]] && rm -f $dirmzremoved/${1}
             shift
        done
     ;;
@@ -174,7 +201,7 @@ case "$1" in
     -u|upgrade) # Upgrade de pacotes
         shift
         _INPUT_NULL_PARAMETER "$1" # Se ta nulo o help precisa ser chamado =)
-        while [[ -n "$1" ]]; do           
+        while [[ -n "$1" ]]; do
             _NAME_FORMAT_PKG "$1" || exit 1 # Função de configuração de entrada!
             _UPGRADE "$1" || exit 1
             shift
@@ -182,16 +209,21 @@ case "$1" in
     ;;
 
     update) # Update do banana
-        _UPDATE_BANANA || exit 1
+        _UPDATE_BANANA && exit 0 || exit 1
     ;;
 
     -r|remove)
         shift # Rebaixa baby
-        _INPUT_NULL_PARAMETER "$1" # Se ta nulo o help precisa ser chamado =) 
+        _INPUT_NULL_PARAMETER "$1" # Se ta nulo o help precisa ser chamado =)
         # Se contiver um dos caracteres da lista, não poderá continuar.
         [[ "$1" =~ .*(\*|@|#|,).* ]] && { echo 'Dont Use * or @ or #'; exit 1 ;}
         while [[ -n "$1" ]]; do
             _PRE_REMOVE "$1" || exit 1
+            retval=${?}
+#           [[ $retval = 0 ]] && _pkg=($(echo $dirmzinstalled/${1}*.mz))
+            [[ $retval = 0 ]] && _pkg=($(echo $dirmzinstalled/${1}*| sed 's|/| |g'|awk '{print $5}'))
+            [[ $retval = 0 ]] && rm -f $dirmzinstalled/${_pkg}
+            [[ $retval = 0 ]] && touch $dirmzremoved/${_pkg}
             shift
         done
         exit 0
@@ -204,6 +236,12 @@ case "$1" in
             _SEARCH_PKG "$1" # Chamando função de check
             shift
         done
+    ;;
+
+    -pl|print)
+        shift # rebaixo
+        _INPUT_NULL_PARAMETER "$1"
+        _PRINT_LIST "$1" || exit 1
     ;;
 
     -V|version) echo "$PRG Version $VERSION" ;;
